const listItems = [
  { id: 1, name: "Pão de Queijo", price: 25.0, quantity: 1 },
  { id: 2, name: "Queijo Minas", price: 35.0, quantity: 2 },
  { id: 3, name: "Doce de Leite", price: 18.5, quantity: 3 },
  { id: 4, name: "Goiabada", price: 15.0, quantity: 2 },
  { id: 5, name: "Tutu de Feijão", price: 20.0, quantity: 1 },
  { id: 6, name: "Feijão Tropeiro", price: 22.0, quantity: 1 },
  { id: 7, name: "Broa de Milho", price: 10.0, quantity: 5 },
  { id: 8, name: "Café Mineiro", price: 30.0, quantity: 1 },
  { id: 9, name: "Frango com Quiabo", price: 25.0, quantity: 1 },
  { id: 10, name: "Linguiça Caseira", price: 35.0, quantity: 2 },
  { id: 11, name: "Farofa", price: 12.0, quantity: 2 },
  { id: 12, name: "Torresmo", price: 18.0, quantity: 1 },
  { id: 13, name: "Vaca Atolada", price: 28.0, quantity: 1 },
  { id: 14, name: "Pé de Moleque", price: 10.0, quantity: 4 },
  { id: 15, name: "Rapadura", price: 8.0, quantity: 3 },
  { id: 16, name: "Banana Passa", price: 15.0, quantity: 2 },
  { id: 17, name: "Cachaça Mineira", price: 50.0, quantity: 1 },
  { id: 18, name: "Arroz com Suã", price: 22.0, quantity: 1 },
  { id: 19, name: "Canjiquinha", price: 18.0, quantity: 2 },
  { id: 20, name: "Bolinho de Chuva", price: 12.0, quantity: 3 },
  { id: 21, name: "Feijão Andu", price: 20.0, quantity: 1 },
  { id: 22, name: "Costelinha de Porco", price: 30.0, quantity: 1 },
  { id: 23, name: "Empadão de Frango", price: 20.0, quantity: 1 },
  { id: 24, name: "Biscoito de Polvilho", price: 8.0, quantity: 4 },
  { id: 25, name: "Frango ao Molho Pardo", price: 35.0, quantity: 1 },
  { id: 26, name: "Requeijão de Corte", price: 18.0, quantity: 2 },
  { id: 27, name: "Pé-de-Moleque", price: 5.0, quantity: 4 },
  { id: 28, name: "Fubá", price: 7.0, quantity: 3 },
  { id: 29, name: "Tropeiro Completo", price: 32.0, quantity: 1 },
  { id: 30, name: "Torresmo de Barriga", price: 20.0, quantity: 2 },
];

export default listItems;
